### ISSUE TITLE
XML documentation warning

### ISSUE THREAD

**Issue by DrDinosaur** [cobbr/SharpSploit#10]
When you build the SharpSploit project, there is a Visual Studio warning because one of the comments in the XML documentation appears to not escape angle brackets. 

Screenshot: https://imgur.com/a/sC3cbON

**Comment by cobbr** [comment]
Thanks for the heads up and the PR @DrDinosaur!

I'll probably just remove those angle bracket characters, rather than all the work to escape them. That is a good trick to know for the future though.

**Comment by cobbr** [comment]
Fixed in 7de36b8e67e873fa440658653145309baeeec45c
