### ISSUE TITLE
Shell doesn't provide data written to the standard error stream

### ISSUE THREAD

**Issue by DrDinosaur** [cobbr/SharpSploit#12]
Currently, ShellExecuteWithPath only returns the standard output. 

Should it also return the standard error by adding the lines that went to the standard error stream to one output string (that contains the data of both streams) in chronological order? 

I don't know how common writing to standard error is and the operator may just care about standard output, so I consider this more of a design choice rather than a bug. 

If you think standard error should be added, I can make a PR.

**Comment by cobbr** [comment]
Hey @DrDinosaur! Yeah I think it would be great to have stderr as well, and would merge that PR.

It would be nice to have them in chronological order, but that may be difficult. If you can do that, that would be even better.

**Comment by cobbr** [comment]
Merged in b5f1a3f21305fe3cf33ba2de8da76ef6f371a271
