### ISSUE TITLE
XML documentation file

### ISSUE THREAD

**Issue by dtrizna** [cobbr/SharpSploit#3]
Hi!

You have a hard-coded XML documentation file path in the 9th line of https://github.com/cobbr/SharpSploit/blob/master/SharpSploit/SharpSploit.csproj

During Project build it's raises CS0016:

![image](https://user-images.githubusercontent.com/15322061/48353314-d0a93380-e697-11e8-9922-9a7e49811fd6.png)

P.S.
In any particular case this can be solved with Visual Studio Project properties > Build > XML documentation file setting:

![image](https://user-images.githubusercontent.com/15322061/48353854-11ee1300-e699-11e8-8bb5-a592935ab8cf.png)

Thanks for your work!

**Comment by cobbr** [comment]
Fixed in bb57db90e53c877979f6ed3977e627f59ad67cbb

Thanks @dtrizna!
