### ISSUE TITLE
RegistryRead and RegistryWrite?

### ISSUE THREAD

**Issue by H011YxW00D** [cobbr/SharpSploit#39]
Hello I was attempting to compile another project (SharpSploitConsole) and was running into errors because these functions do not appear to exist anymore in your code however they're still listed in the API docs. I can hit up the other maintainer for the console app but just wondered if there is a workaround or different code I could use.
Example 1: var a = SharpSploit.Enumeration.Host.RegistryRead(request[1]);
Example2: var a = SharpSploit.Enumeration.Host.RegistryWrite(request[1], request[2]);

**Comment by cobbr** [comment]
Hey @H011YxW00D , the documentation likely needs to be updated. Check out SharpSploit.Enumeration.Registry: https://github.com/cobbr/SharpSploit/blob/master/SharpSploit/Enumeration/Registry.cs

**Comment by H011YxW00D** [comment]
Yeah just saw this lol on another thread sorry. I can change that code to: 
https://github.com/anthemtotheego/SharpSploitConsole/pull/1/commits/181ca22f9331d1113b09848158606cbcdebb980e

Thanks Again!

**Comment by cobbr** [comment]
no problem!
