### ISSUE TITLE
how to update powerkatz*.dll.comp

### ISSUE THREAD

**Issue by johnjohnsp1** [cobbr/SharpSploit#47]
Hello, awesome tools and appreciate the sharing.
my problem trying to update latest mimikatz's dlls is that i dont get how you generate both powerkatzx64.dll.comp and powerkatzx86.dll.comp.
both original dll's are generated from the mimikatz project from benjamin delpy, using second_release build option.
on the description you describe with:
"powerkatz_x64.dll.comp  // Mimikatz 64-bit dll, compressed using the built-in System.IO.Compression library"
how can you compress the dll ? the System.IO.Compression is used on C# project but not with dll's already compiled....

thanks

**Comment by rasta-mouse** [comment]
https://github.com/PowerShellMafia/PowerSploit/blob/master/ScriptModification/Out-CompressedDll.ps1

**Comment by johnjohnsp1** [comment]
thanks for the info, I will try with that.
