### ISSUE TITLE
BypassUAC doesnt spawn a process

### ISSUE THREAD

**Issue by Kurainu** [cobbr/SharpSploit#48]
The BypassUAC Method doesnt spawns the specfied the Process and only show Access Denied when calling CreateProcesswithLogonW both normal und running as an Administrator

The same with the GetSystem Method
![image](https://user-images.githubusercontent.com/15718492/80312862-f96bad00-87e7-11ea-8c28-2d8d7fd97ccb.png)

What im doing Wrong here or i am correctly using it?

windows version:
![image](https://user-images.githubusercontent.com/15718492/80312937-464f8380-87e8-11ea-890a-ab7140921b74.png)

and using Visual Studio 2019 and the latest Version of Sharpsploit

**Comment by rasta-mouse** [comment]
Hi @Kurainu.

This Task uses Token Duplication trickery, which has been [patched](https://www.tiraniddo.dev/2018/10/farewell-to-token-stealing-uac-bypass.html) in later versions of Windows (including 1903).

Closing this as expected behaviour.
