### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by DrawTrustDraw** [cobbr/SharpSploit#9]
Windows7 VS 2015 community, SharpSploit project load failed.
Output Error:
\SharpSploit\SharpSploit.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\user\Downloads\SharpSploit-master\SharpSploit-master\SharpSploit\SharpSploit.csproj

**Comment by cobbr** [comment]
Hey @DrawTrustDraw , have you tried compiling on VS 2017? That's the environment SharpSploit was developed in.

**Comment by DrawTrustDraw** [comment]
Thanks

**Comment by cobbr** [comment]
No problem!
